// This file is auto-generated by Alva.
// Do not edit manually.

import type { AlvaResult } from "./types";

export type PageEventLiveEvents = {
  "page.echo": {
    input: Record<string, unknown>;
    output: AlvaResult<void>;
  };

  "page.invalid": {
    input: Record<string, unknown>;
    output: AlvaResult<void>;
  };

};
