// This file is auto-generated by Alva.
// Do not edit manually.

import type { AlvaResult } from "./types";

export type PageEventsLiveEvents = {
  "support.join_chat": {
    input: Record<string, unknown>;
    output: AlvaResult<void>;
  };

  "support.reset_chat": {
    input: Record<string, unknown>;
    output: AlvaResult<void>;
  };

};
