defmodule Alva.Codegen.DtoGenerator do
  @moduledoc since: "0.1.0"
  @moduledoc """
  Generates TypeScript interfaces for Ash resources and their filter types.

  Produces the `types.ts` file that defines TypeScript interfaces for each
  Ash resource, plus filter interfaces for resources with `enable_filter: true`.
  Also provides `output_type/2` to determine the return type of an event.

  See `Mix.Tasks.Alva.Codegen` for the full code generation pipeline.
  """

  alias Alva.Codegen.TypeMapper

  @doc """
  Generates the complete `types.ts` content including base filter types,
  resource filter interfaces, and resource data interfaces.
  """
  @doc since: "0.1.0"
  def generate_types_ts(resources, events_map \\ nil) do
    interfaces =
      resources
      |> Enum.map_join("\n\n", &generate_interface/1)

    filter_resources =
      if events_map do
        involved =
          events_map
          |> Enum.filter(fn {_name, {_res, event_def}} ->
            Map.get(event_def, :enable_filter, false)
          end)
          |> Enum.map(fn {_name, {res, _event}} -> res end)

        gather_related_resources(involved, MapSet.new(involved))
        |> Enum.to_list()
      else
        resources
      end

    filter_interfaces =
      filter_resources
      |> Enum.map_join("\n\n", &generate_filter_interface/1)

    """
    // This file is auto-generated by Alva.
    // Do not edit manually.

    export type AlvaResult<T> =
      | { ok: true; data: T; meta?: Record<string, any> }
      | { ok: false; error: any; meta?: Record<string, any> };

    export interface PaginationInput {
      limit?: number;
      offset?: number;
      after?: string;
      before?: string;
      count?: boolean;
    }

    export interface BaseFieldFilter<T> {
      eq?: T | null;
      not_eq?: T | null;
      in?: T[] | null;
      is_nil?: boolean | null;
      less_than?: T | null;
      greater_than?: T | null;
      less_than_or_equal?: T | null;
      greater_than_or_equal?: T | null;
    }

    export interface StringFieldFilter extends BaseFieldFilter<string> {
      contains?: string | null;
      ilike?: string | null;
      like?: string | null;
    }

    export interface IntFieldFilter extends BaseFieldFilter<number> {}

    export interface BooleanFieldFilter {
      eq?: boolean | null;
      not_eq?: boolean | null;
      is_nil?: boolean | null;
    }

    #{filter_interfaces}

    #{interfaces}
    """
  end

  defp gather_related_resources([], visited), do: visited

  defp gather_related_resources([resource | rest], visited) do
    related =
      Ash.Resource.Info.public_relationships(resource)
      |> Enum.map(& &1.destination)
      |> Enum.reject(&MapSet.member?(visited, &1))

    gather_related_resources(rest ++ related, MapSet.union(visited, MapSet.new(related)))
  end

  @doc """
  Determines the TypeScript output type for a given event.

  Returns `"InterfaceName[]"` for list reads, or `"InterfaceName"` for
  single-record reads, lookups, and mutations.
  """
  @doc since: "0.1.0"
  def output_type(resource, event_def) do
    action = Ash.Resource.Info.action(resource, event_def.action)
    interface = interface_name(resource)

    if action.type == :read and is_nil(event_def.lookup) and not action.get? do
      "#{interface}[]"
    else
      interface
    end
  end

  @doc """
  Derives the TypeScript interface name from an Ash resource module.

  Uses the last segment of the module name (e.g. `MyApp.Catalog.Product` → `Product`).
  """
  @doc since: "0.1.0"
  def interface_name(resource) do
    resource |> Module.split() |> List.last()
  end

  defp generate_interface(resource) do
    name = interface_name(resource)
    policy_fields = resource_policy_fields(resource)
    {fields, rels} = public_fields_and_relationships(resource)

    fields_ts =
      Enum.map(fields, fn field ->
        optional? = optional?(field, policy_fields)
        ts_type = TypeMapper.map_type(field.type, Map.get(field, :constraints, []))
        format_field(field.name, ts_type, optional?)
      end)

    rels_ts =
      Enum.map(rels, fn rel ->
        # Relationships might not always be loaded
        dest_name = interface_name(rel.destination)
        ts_type = if rel.cardinality == :many, do: "#{dest_name}[]", else: dest_name
        format_field(rel.name, ts_type, true)
      end)

    all_fields = Enum.join(fields_ts ++ rels_ts, "\n")

    """
    export interface #{name} {
    #{all_fields}
    }
    """
  end

  defp optional?(field, policy_fields) do
    field.name in policy_fields or Map.get(field, :allow_nil?, true)
  end

  defp format_field(name, type, true = _optional?), do: "  #{name}?: #{type};"
  defp format_field(name, type, false = _optional?), do: "  #{name}: #{type};"

  defp generate_filter_interface(resource) do
    name = interface_name(resource)
    filter_name = "#{name}Filter"
    {fields, rels} = public_fields_and_relationships(resource)

    fields_ts =
      Enum.map(fields, fn field ->
        ts_type = TypeMapper.map_type(field.type, Map.get(field, :constraints, []))

        filter_op_type =
          case ts_type do
            "string" -> "StringFieldFilter"
            "number" -> "IntFieldFilter"
            "boolean" -> "BooleanFieldFilter"
            _ -> "BaseFieldFilter<#{ts_type}>"
          end

        "  #{field.name}?: #{filter_op_type} | null;"
      end)

    rels_ts =
      Enum.map(rels, fn rel ->
        dest_name = interface_name(rel.destination)
        dest_filter = "#{dest_name}Filter"
        "  #{rel.name}?: #{dest_filter} | null;"
      end)

    all_fields = Enum.join(fields_ts ++ rels_ts, "\n")

    """
    export interface #{filter_name} {
      and?: #{filter_name}[];
      or?: #{filter_name}[];
      not?: #{filter_name};
    #{all_fields}
    }
    """
  end

  defp resource_policy_fields(resource) do
    if Code.ensure_loaded?(Ash.Policy.Info) and
         function_exported?(Ash.Policy.Info, :field_policies, 1) do
      (apply(Ash.Policy.Info, :field_policies, [resource]) || [])
      |> Enum.flat_map(& &1.fields)
      |> Enum.uniq()
    else
      []
    end
  end

  defp public_fields_and_relationships(resource) do
    fields =
      Ash.Resource.Info.public_attributes(resource) ++
        Ash.Resource.Info.public_calculations(resource) ++
        Ash.Resource.Info.public_aggregates(resource)

    rels = Ash.Resource.Info.public_relationships(resource)

    {fields, rels}
  end
end
