defmodule Alva.Codegen.PageEventsGenerator do
  def generate!(module, page_events) do
    output_dir = Application.get_env(:alva, :output_dir, "assets/js/alva")
    File.mkdir_p!(output_dir)

    module_name = module |> Module.split() |> List.last()
    
    events_content =
      page_events
      |> Enum.map(fn
        {event_name, _callback} ->
          generate_event(event_name, %{input: "Record<string, unknown>", output: "void"})

        {event_name, _callback, types} ->
          types = Map.merge(%{input: "Record<string, unknown>", output: "void"}, types)
          generate_event(event_name, types)
      end)
      |> Enum.join("\n")

    content = """
// This file is auto-generated by Alva.
// Do not edit manually.

import type { LiveResult } from "./types";

export type #{module_name}Events = {
#{events_content}
};
"""

    filename = "#{module_name}.events.ts"
    file_path = Path.join(output_dir, filename)
    
    case File.read(file_path) do
      {:ok, existing} when existing == content ->
        :ok # Skip write to avoid mtime updates
      _ ->
        File.write!(file_path, content)
    end
  end
  
  defp generate_event(event_name, types) do
    """
      "#{event_name}": {
        input: #{Map.get(types, :input)};
        output: LiveResult<#{Map.get(types, :output)}>;
      };
    """
  end
end
