defmodule Alva.Codegen.PageEventsGenerator do
  def generate!(_module, page_events) when not is_list(page_events) or page_events == [], do: :ok
  
  def generate!(module, page_events) do
    output_dir = Application.get_env(:alva, :output_dir, "assets/js/alva")
    File.mkdir_p!(output_dir)

    module_name = module |> Module.split() |> List.last()
    
    events_content =
      page_events
      |> Enum.map(fn
        {event_name, _callback} ->
          generate_event(event_name, %{})

        {event_name, _callback, input_types} ->
          generate_event(event_name, input_types)
      end)
      |> Enum.join("\n")

    content = """
// This file is auto-generated by Alva.
// Do not edit manually.

import type { LiveResult } from "./types";

export type #{module_name}Events = {
#{events_content}
};
"""

    filename = "#{module_name}.events.ts"
    file_path = Path.join(output_dir, filename)
    
    case File.read(file_path) do
      {:ok, existing} when existing == content ->
        :ok # Skip write to avoid mtime updates
      _ ->
        File.write!(file_path, content)
    end
  end
  
  defp generate_event(event_name, input_types) do
    input_ts = build_ts_input(input_types)
    """
      "#{event_name}": {
        input: #{input_ts};
        output: LiveResult<void>;
      };
    """
  end

  defp build_ts_input(input_types) when map_size(input_types) == 0 do
    "Record<string, never>"
  end

  defp build_ts_input(input_types) do
    fields =
      Enum.map(input_types, fn {key, type} ->
        ts_type = map_type(type)
        "#{key}?: #{ts_type}"
      end)
      |> Enum.join("; ")

    "{ #{fields} }"
  end

  defp map_type(:string), do: "string"
  defp map_type(:boolean), do: "boolean"
  defp map_type(:integer), do: "number"
  defp map_type(_), do: "unknown"
end
