defmodule Mix.Tasks.Alva.Codegen do
  @shortdoc "Generates TypeScript bindings for LiveVue events"
  @moduledoc """
  Generates TypeScript bindings for LiveVue events defined in Ash resources.

  Reads domains configured in `:alva, :domains` or searches the application.
  Outputs generated files to `:alva, :output_dir` (defaults to `assets/js/alva`).
  """

  use Mix.Task

  @impl true
  def run(_args) do
    Mix.Task.run("compile")

    app = Mix.Project.config()[:app]
    
    domains = 
      Application.get_env(:alva, :domains, []) ++ 
      Application.get_env(app, :ash_domains, [])
      |> Enum.uniq()

    output_dir = Application.get_env(:alva, :output_dir, "assets/js/alva")

    if domains == [] do
      Mix.shell().info("No Ash domains found. Please configure config :#{app}, ash_domains: [...]")
    else
      File.mkdir_p!(output_dir)
      
      events_map = gather_events(domains)
      
      generate_events_ts(events_map, output_dir)
      generate_client_ts(output_dir)
      
      Mix.shell().info("Successfully generated TypeScript bindings in #{output_dir}")
    end
  end

  defp gather_events(domains) do
    Enum.reduce(domains, %{}, fn domain, acc ->
      domain_map = Alva.Domain.Info.alva_event_map(domain)
      Map.merge(acc, domain_map)
    end)
  end

  defp generate_events_ts(events_map, output_dir) do
    events_content =
      events_map
      |> Enum.map(fn {event_name, _tuple} ->
        """
          "#{event_name}": {
            input: any;
            output: any;
          };
        """
      end)
      |> Enum.join("\n")

    content = """
    // This file is auto-generated by Alva.
    // Do not edit manually.

    export type AlvaEvents = {
    #{events_content}
    };
    """

    write_file!(output_dir, "events.ts", content)
  end

  defp generate_client_ts(output_dir) do
    content = """
    // This file is auto-generated by Alva.
    import type { AlvaEvents } from "./events";
    import { use_alva_api } from "alva/use_alva_api";

    export const api = use_alva_api<AlvaEvents>();
    """

    write_file!(output_dir, "client.ts", content)
  end

  defp write_file!(output_dir, filename, content) do
    file_path = Path.join(output_dir, filename)
    File.write!(file_path, content)
  end
end
