defmodule Mix.Tasks.Alva.Codegen do
  @shortdoc "Generates TypeScript bindings for LiveVue events"
  @moduledoc """
  Generates TypeScript bindings for LiveVue events defined in Ash resources.

  Reads the host application's configured `ash_domains`.
  Outputs generated files to `:alva, :output_dir` (defaults to `assets/js/alva`).
  """

  use Mix.Task

  @impl true
  def run(_args) do
    Mix.Task.run("compile")

    app = Mix.Project.config()[:app]
    output_dir = Application.get_env(:alva, :output_dir, "assets/js/alva")

    if Ash.Info.domains(app) == [] do
      Mix.shell().info(
        "No Ash domains found. Please configure config :#{app}, ash_domains: [...]"
      )
    else
      composables_dir = Path.join(output_dir, "composables")
      File.mkdir_p!(composables_dir)
      File.mkdir_p!(output_dir)

      events_map = Alva.Registry.event_map(app)
      signal_map = Alva.Registry.registry(app).signal_map

      resources =
        events_map
        |> Map.values()
        |> Enum.map(fn {resource, _event} -> resource end)
        |> Enum.uniq()

      generate_types_ts(resources, events_map, output_dir)
      generate_events_ts(events_map, output_dir)
      generate_signals_ts(signal_map, events_map, output_dir)
      generate_use_alva_api_ts(events_map, composables_dir)
      generate_use_alva_form_ts(composables_dir)
      generate_use_alva_upload_ts(composables_dir)
      generate_ash_ts(signal_map, composables_dir)
      generate_index_ts(output_dir)

      Mix.shell().info("Successfully generated TypeScript SDK in #{output_dir}")
    end
  end

  defp generate_types_ts(resources, events_map, output_dir) do
    content = Alva.Codegen.DtoGenerator.generate_types_ts(resources, events_map)
    write_file!(output_dir, "types.ts", content)
  end

  defp generate_events_ts(events_map, output_dir) do
    events_content =
      events_map
      |> Enum.map_join("\n", fn {event_name, {resource, event_def}} ->
        output_type = Alva.Codegen.DtoGenerator.output_type(resource, event_def)
        action = Ash.Resource.Info.action(resource, event_def.action)

        input_shape =
          Alva.Codegen.InputContract.generate_input_shape(
            resource,
            event_def,
            action,
            "            "
          )

        """
          "#{event_name}": {
            input: #{input_shape};
            output: AlvaResult<Types.#{output_type}>;
          };
        """
      end)

    content = """
    // This file is auto-generated by Alva.
    // Do not edit manually.

    import type { AlvaResult } from "./types";
    import type * as Types from "./types";

    export type AlvaEvents = {
    #{events_content}
    };
    """

    write_file!(output_dir, "events.ts", content)
  end

  defp generate_signals_ts(signal_map, events_map, output_dir) do
    subs_content =
      signal_map
      |> Enum.map_join("\n", fn {_key, {resource, signal_def}} ->
        payload_prop = generate_signal_payload_prop(signal_def, events_map, resource)

        """
          "#{signal_def.name}": {
            #{payload_prop}
          };
        """
      end)

    content = """
    // This file is auto-generated by Alva.
    // Do not edit manually.

    import type * as Types from "./types";

    export type AlvaSignals = {
    #{subs_content}
    };
    """

    write_file!(output_dir, "signals.ts", content)
  end

  defp generate_signal_payload_prop(_signal_def, _events_map, resource) do
    output_type = resource |> Module.split() |> List.last()
    "payload: Types.#{output_type};"
  end

  defp generate_use_alva_api_ts(events_map, composables_dir) do
    methods =
      events_map
      |> Enum.map_join("\n", fn {event_name, {_resource, _event_def}} ->
        """
              "#{event_name}": (payload: AlvaEvents["#{event_name}"]["input"]): AlvaEvents["#{event_name}"]["output"] => {
                return new Promise((resolve) => {
                  live.pushEvent("#{event_name}", payload, (reply: AlvaEvents["#{event_name}"]["output"]) => {
                    if (reply.ok) {
                      config?.onSuccess?.(reply.data, "#{event_name}");
                    } else {
                      config?.onError?.(reply.error, "#{event_name}");
                    }
                    resolve(reply);
                  });
                });
              },
        """
      end)

    content = """
    // This file is auto-generated by Alva.
    // Do not edit manually.

    import { useLiveVue } from "live_vue";
    import type { AlvaEvents } from "../events";

    export type AlvaError = {
        type: string;
        message: string;
        code?: string;
        fields?: Record<string, string[]>;
    };

    export interface AlvaApiConfig {
        onError?: (error: AlvaError, event: string) => void;
        onSuccess?: (data: unknown, event: string) => void;
    }

    export function useAlvaApi(config?: AlvaApiConfig) {
        const live = useLiveVue();

        return {
    call: {
    #{methods}
    }
        };
    }
    """

    write_file!(composables_dir, "useAlvaApi.ts", content)
  end

  defp generate_use_alva_form_ts(composables_dir) do
    content = """
    // This file is auto-generated by Alva.
    // Do not edit manually.

    import { reactive } from "vue";
    import { useLiveForm, type Form, type UseLiveFormReturn } from "live_vue";
    import type { AlvaEvents } from "../events";

    export type AlvaFormOptions<FormValues, EventKeys> = {
        initialValues: FormValues;
        validateEvent?: EventKeys;
        debounceMs?: number;
        uploads?: Record<string, { getFileReferences: () => string[] }>;
        onOptimisticSubmit?: (formData: FormValues) => (() => void) | void;
    };

    type AlvaFormReturn<K extends keyof AlvaEvents, FormValues extends object> =
        UseLiveFormReturn<FormValues> & {
            submit: () => Promise<AlvaEvents[K]["output"]>;
        };

    function clearFormErrors(errors: Record<string, string[]>) {
        for (const key of Object.keys(errors)) {
            delete errors[key];
        }
    }

    export function useAlvaForm<
        K extends keyof AlvaEvents,
        FormValues extends object = AlvaEvents[K]["input"],
    >(
        submitEvent: K,
        options: AlvaFormOptions<FormValues, keyof AlvaEvents>,
    ): AlvaFormReturn<K, FormValues> {
        const pseudoForm = reactive({
            name: submitEvent as string,
            values: JSON.parse(JSON.stringify(options.initialValues)),
            errors: {} as Record<string, string[]>,
            valid: true,
        }) as Form<FormValues>;

        const liveForm = useLiveForm(pseudoForm, {
            submitEvent: submitEvent as string,
            changeEvent: (options.validateEvent as string) || null,
            debounceInMiliseconds: options.debounceMs || 300,
            prepareData: (data: any) => {
                if (options.uploads) {
                    for (const [key, upload] of Object.entries(options.uploads)) {
                        data[key] = upload.getFileReferences();
                    }
                }
                return data;
            }
        });

        const originalSubmit = liveForm.submit;

        const submit = async (): Promise<AlvaEvents[K]["output"]> => {
            const rollbackFn = options.onOptimisticSubmit?.(pseudoForm.values);
            let result: any;

            try {
                result = await originalSubmit();
            } catch (e: any) {
                result = { ok: false, error: { type: "unknown", message: e.message || String(e) } };
            }

            if (!result || !result.ok) {
                if (rollbackFn) rollbackFn();

                if (result?.error?.fields) {
                    clearFormErrors(pseudoForm.errors);
                    Object.assign(pseudoForm.errors, result.error.fields);
                }
            } else {
                clearFormErrors(pseudoForm.errors);
            }

            return result;
        };

        return {
            ...liveForm,
            submit,
        } as AlvaFormReturn<K, FormValues>;
    }
    """

    write_file!(composables_dir, "useAlvaForm.ts", content)
  end

  defp generate_use_alva_upload_ts(composables_dir) do
    content = """
    // This file is auto-generated by Alva.
    // Do not edit manually.

    import { computed, ref, watch } from "vue";
    import { useLiveUpload, useLiveVue } from "live_vue";

    export type UploadEntry = {
        ref: string;
        client_name?: string;
        client_size?: number;
        client_type?: string;
        name?: string;
        size?: number;
        type?: string;
        progress: number;
        error?: string;
    };

    export type AlvaUploadOptions = {
        maxFiles?: number;
        maxSize?: number;
    };

    export type AlvaUploadDispatchContext = {
        files: UploadEntry[];
        references: string[];
        primaryReference: string;
    };

    const ALVA_UPLOAD_CHANGE_EVENT = "alva.validate_upload";
    const ALVA_UPLOAD_SUBMIT_EVENT = "alva.save_upload";

    type UploadConfigShape = {
        ref: string;
        name: string;
        accept: string | false;
        max_entries: number;
        auto_upload: boolean;
        entries: UploadEntry[];
        errors: unknown[];
    };

    export function useAlvaUpload(name: string, options?: AlvaUploadOptions) {
        const live = useLiveVue();
        const uploadProps = live.vue?.props as Record<string, unknown> | null | undefined;

        const getUploadConfig = (): UploadConfigShape | null => {
            const directConfig = uploadProps?.[name];
            if (isUploadConfig(directConfig)) return directConfig;

            const nested = uploadProps?.uploads;
            if (nested && typeof nested === "object" && !Array.isArray(nested)) {
                const nestedConfig = (nested as Record<string, unknown>)[name];
                if (isUploadConfig(nestedConfig)) return nestedConfig;
            }
            return null;
        };

        const config = getUploadConfig();

        if (!config) {
            return missingUpload(name);
        }

        const upload = useLiveUpload(getUploadConfig, {
            changeEvent: ALVA_UPLOAD_CHANGE_EVENT,
            submitEvent: ALVA_UPLOAD_SUBMIT_EVENT,
            ...(options || {}),
        }) as any;

        const files = computed<UploadEntry[]>(() => upload.entries?.value || []);
        const errors = computed(() => upload.errors?.value || []);

        const progress = computed(() => {
            if (files.value.length === 0) return 0;
            let totalSize = 0;
            let totalUploaded = 0;
            for (const file of files.value) {
                const size = file.client_size ?? file.size ?? 0;
                totalSize += size;
                totalUploaded += size * ((file.progress || 0) / 100);
            }
            return totalSize === 0 ? 0 : Math.round((totalUploaded / totalSize) * 100);
        });

        const enforceLimits = () => {
            if (!options || !upload.cancel) return;
            if (options.maxFiles && files.value.length > options.maxFiles) {
                files.value.slice(options.maxFiles).forEach((f) => upload.cancel(f.ref));
            }
            if (options.maxSize) {
                files.value.forEach((f) => {
                    const size = f.client_size ?? f.size ?? 0;
                    if (size > options.maxSize!) upload.cancel(f.ref);
                });
            }
        };

        watch(files, enforceLimits, { deep: true, immediate: true });

        const getFileReferences = () => files.value.map((f) => f.ref);

        const waitForCompletion = (): Promise<AlvaUploadDispatchContext> => {
            return new Promise((resolve, reject) => {
                let settled = false;
                let stop: (() => void) | undefined;

                const settle = (cb: () => void) => {
                    if (settled) return;
                    settled = true;
                    stop?.();
                    cb();
                };

                const tryComplete = () => {
                    if (files.value.length === 0 || progress.value !== 100) return;
                    const refs = getFileReferences();
                    const primary = refs[0];
                    if (!primary) {
                        settle(() => reject(new Error("No uploaded file reference was produced.")));
                        return;
                    }
                    settle(() => resolve({ files: [...files.value], references: refs, primaryReference: primary }));
                };

                tryComplete();
                if (settled) return;
                stop = watch([files, progress], tryComplete, { deep: true });
            });
        };

        const dispatch = async <T>(
            submit: (ctx: AlvaUploadDispatchContext) => Promise<T>,
            opts: { clear?: boolean } = {},
        ) => {
            try {
                const ctx = await waitForCompletion();
                return await submit(ctx);
            } finally {
                if (opts.clear !== false) upload.clear?.();
            }
        };

        return { ...upload, files, errors, progress, getFileReferences, dispatch };
    }

    function uploadEntrySize(file: UploadEntry) {
        return file.client_size ?? file.size ?? 0;
    }

    function isUploadConfig(value: unknown): value is UploadConfigShape {
        return Boolean(
            value && typeof value === "object" &&
            typeof (value as UploadConfigShape).ref === "string" &&
            typeof (value as UploadConfigShape).name === "string" &&
            Array.isArray((value as UploadConfigShape).entries) &&
            Array.isArray((value as UploadConfigShape).errors)
        );
    }

    function missingUpload(name: string) {
        const files = ref<UploadEntry[]>([]);
        const errors = computed(() => []);
        const progress = computed(() => 0);
        const warn = () => {
            console.warn(
                `[alva/useAlvaUpload] Missing LiveView upload config for "${name}". ` +
                `Pass the matching upload prop to the LiveVue component.`
            );
        };
        return {
            name, entries: files, files, errors, progress,
            showFilePicker: warn, cancel: () => {}, clear: () => {},
            getFileReferences: () => [],
            dispatch: async () => { warn(); throw new Error("Missing upload config"); },
        };
    }
    """

    write_file!(composables_dir, "useAlvaUpload.ts", content)
  end

  defp generate_ash_ts(signal_map, composables_dir) do
    signal_names =
      signal_map
      |> Map.values()
      |> Enum.map_join(" | ", fn {_resource, signal_def} ->
        ~s("#{signal_def.name}")
      end)

    content = """
    // This file is auto-generated by Alva.
    // Do not edit manually.

    import { onUnmounted } from "vue";
    import { useLiveVue, useLiveEvent } from "live_vue";
    import type { AlvaSignals } from "../signals";

    export const ash = {
        on: <K extends keyof AlvaSignals>(
            name: K,
            input: Record<string, never>,
            callback: (payload: AlvaSignals[K]["payload"]) => void
        ) => {
            const live = useLiveVue();

            live.pushEvent(
                "alva:subscribe_signal",
                { name, input },
                () => {}
            );

            useLiveEvent(name as string, callback);

            onUnmounted(() => {
                live.pushEvent(
                    "alva:unsubscribe_signal",
                    { name, input },
                    () => {}
                );
            });
        }
    };
    """

    write_file!(composables_dir, "ash.ts", content)
  end

  defp generate_index_ts(output_dir) do
    content = """
    // This file is auto-generated by Alva.
    // Do not edit manually.

    export { useAlvaApi } from "./composables/useAlvaApi";
    export { useAlvaForm } from "./composables/useAlvaForm";
    export { useAlvaUpload } from "./composables/useAlvaUpload";
    export { ash } from "./composables/ash";
    export type { AlvaApiConfig, AlvaError } from "./composables/useAlvaApi";
    export type { AlvaFormOptions } from "./composables/useAlvaForm";
    export type { AlvaUploadOptions, AlvaUploadDispatchContext, UploadEntry } from "./composables/useAlvaUpload";
    export type { AlvaEvents } from "./events";
    export type { AlvaSignals } from "./signals";
    """

    write_file!(output_dir, "index.ts", content)
  end

  defp write_file!(output_dir, filename, content) do
    file_path = Path.join(output_dir, filename)
    File.write!(file_path, content)
  end
end
