// This file is auto-generated by Alva.
// Do not edit manually.

import { onUnmounted } from "vue";
import { useLiveVue, useLiveEvent } from "live_vue";
import type { AlvaSignals } from "../signals";

export const ash = {
    on: {
      "demo_notifications.sent": (input: Record<string, never>, callback: (payload: AlvaSignals["demo_notifications.sent"]["payload"]) => void) => {
        const live = useLiveVue();

        live.pushEvent(
            "alva:subscribe_signal",
            { name: "demo_notifications.sent", input },
            () => {}
        );

        useLiveEvent("demo_notifications.sent", callback);

        onUnmounted(() => {
            live.pushEvent(
                "alva:unsubscribe_signal",
                { name: "demo_notifications.sent", input },
                () => {}
            );
        });
      },

    }
};
