// This file is auto-generated by Alva.
// Do not edit manually.

import { onUnmounted } from "vue";
import { useLiveVue, useLiveEvent } from "live_vue";
import type { AlvaSignals } from "../signals";

export const ash = {
    on: <K extends keyof AlvaSignals>(
        name: K,
        input: Record<string, never>,
        callback: (payload: AlvaSignals[K]["payload"]) => void
    ) => {
        const live = useLiveVue();

        live.pushEvent(
            "alva:subscribe_signal",
            { name, input },
            () => {}
        );

        useLiveEvent(name as string, callback);

        onUnmounted(() => {
            live.pushEvent(
                "alva:unsubscribe_signal",
                { name, input },
                () => {}
            );
        });
    }
};
