// This file is auto-generated by Alva.
// Do not edit manually.

import { ref, watch, onUnmounted, type Ref, type WatchSource } from "vue";
import { useLiveVue, useLiveEvent } from "live_vue";
import type { AlvaEvents } from "../events";
import type { AlvaError } from "./useAlva";

export interface AlvaQueryOptions {
    debounceMs?: number;
    pollIntervalMs?: number | Ref<number> | (() => number);
    autoRefreshOnSignal?: string | string[];
}

export interface AlvaQueryReturn<Output> {
    data: Ref<Output | null>;
    loading: Ref<boolean>;
    error: Ref<AlvaError | null>;
    refetch: () => Promise<void>;
}

export function useAlvaQuery<
    K extends keyof AlvaEvents,
    Input = AlvaEvents[K]["input"],
    Output = Extract<AlvaEvents[K]["output"], { ok: true }> extends { data: infer D } ? D : never
>(
    queryEvent: K,
    inputGetter: WatchSource<Input>,
    options: AlvaQueryOptions = {}
): AlvaQueryReturn<Output> {
    let live: any = null;
    try {
        live = useLiveVue();
    } catch (_e) {
        live = null;
    }
    const data = ref<Output | null>(null) as Ref<Output | null>;
    const loading = ref(false);
    const error = ref<AlvaError | null>(null);

    const debounceMs = options.debounceMs ?? 0;
    let timeoutId: any;
    let currentRequestId = 0;
    let pollTimer: any;

    const fetchQuery = async (currentInput: Input) => {
        const requestId = ++currentRequestId;
        
        return new Promise<void>((resolve) => {
            if (!live || typeof live.pushEvent !== "function") {
                loading.value = false;
                return resolve();
            }

            live.pushEvent(queryEvent as string, currentInput as any, (reply: any) => {
                if (requestId !== currentRequestId) return resolve();

                loading.value = false;
                if (reply && reply.ok) {
                    data.value = reply.data;
                    error.value = null;
                } else if (reply && !reply.ok) {
                    error.value = reply.error || { type: "error", message: "Query failed" };
                }
                resolve();
            });
        });
    };

    const getCurrentInput = (): Input => {
        return typeof inputGetter === "function" ? (inputGetter as any)() : (inputGetter as any).value;
    };

    const debouncedFetch = (currentInput: Input) => {
        loading.value = true;
        if (debounceMs > 0) {
            clearTimeout(timeoutId);
            timeoutId = setTimeout(() => {
                fetchQuery(currentInput);
            }, debounceMs);
        } else {
            fetchQuery(currentInput);
        }
    };

    watch(inputGetter, (newInput) => {
        debouncedFetch(newInput);
    }, { deep: true, immediate: true });

    const getPollInterval = (): number => {
        if (!options.pollIntervalMs) return 0;
        if (typeof options.pollIntervalMs === "function") return options.pollIntervalMs();
        if (typeof options.pollIntervalMs === "object" && options.pollIntervalMs !== null && "value" in options.pollIntervalMs) {
            return (options.pollIntervalMs as Ref<number>).value;
        }
        return Number(options.pollIntervalMs) || 0;
    };

    const setupPollTimer = () => {
        if (pollTimer) {
            clearInterval(pollTimer);
            pollTimer = null;
        }
        const interval = getPollInterval();
        if (interval > 0) {
            pollTimer = setInterval(() => {
                fetchQuery(getCurrentInput());
            }, interval);
        }
    };

    if (typeof options.pollIntervalMs === "function" || (typeof options.pollIntervalMs === "object" && options.pollIntervalMs !== null && "value" in options.pollIntervalMs)) {
        watch(() => getPollInterval(), () => {
            setupPollTimer();
        }, { immediate: true });
    } else {
        setupPollTimer();
    }

    if (options.autoRefreshOnSignal) {
        const signals = Array.isArray(options.autoRefreshOnSignal)
            ? options.autoRefreshOnSignal
            : [options.autoRefreshOnSignal];
        for (const sig of signals) {
            useLiveEvent(sig, () => {
                fetchQuery(getCurrentInput());
            });
        }
    }

    onUnmounted(() => {
        if (pollTimer) clearInterval(pollTimer);
    });

    return {
        data,
        loading,
        error,
        refetch: async () => {
            loading.value = true;
            await fetchQuery(getCurrentInput());
        }
    };
}
