// This file is auto-generated by Alva.
// Do not edit manually.

import { ref, watch } from "vue";
import { useAlvaQuery, type AlvaQueryOptions } from "./useAlvaQuery";
import type { AlvaEvents } from "../events";

export function useAlvaPaginatedQuery<K extends keyof AlvaEvents>(
    eventName: K,
    inputGetter: () => AlvaEvents[K]["input"],
    options?: AlvaQueryOptions & { pageSize?: number }
) {
    const page = ref(1);
    const items = ref<any[]>([]);
    const hasMore = ref(true);
    const loadingMore = ref(false);

    const pageSize = options?.pageSize || 10;

    const queryInput = () => {
        const baseInput = (inputGetter() || {}) as Record<string, any>;
        return {
            ...baseInput,
            page: { offset: (page.value - 1) * pageSize, limit: pageSize }
        } as AlvaEvents[K]["input"];
    };

    const query = useAlvaQuery(eventName, queryInput, options);

    watch(query.data, (newData) => {
        if (Array.isArray(newData)) {
            if (page.value === 1) {
                items.value = newData;
            } else {
                items.value = [...items.value, ...newData];
            }
            hasMore.value = newData.length >= pageSize;
        }
    }, { immediate: true });

    const loadNextPage = async () => {
        if (!hasMore.value || loadingMore.value) return;
        loadingMore.value = true;
        page.value += 1;
        await query.refetch();
        loadingMore.value = false;
    };

    const reset = () => {
        page.value = 1;
        items.value = [];
        hasMore.value = true;
        query.refetch();
    };

    return {
        ...query,
        items,
        page,
        hasMore,
        loadingMore,
        loadNextPage,
        reset
    };
}
