// This file is auto-generated by Alva.
// Do not edit manually.

import { reactive } from "vue";
import { useLiveForm, type Form, type UseLiveFormReturn } from "live_vue";
import type { AlvaEvents } from "../events";

export type AlvaFormOptions<FormValues, EventKeys> = {
    initialValues: FormValues;
    validateEvent?: EventKeys;
    debounceMs?: number;
    uploads?: Record<string, { getFileReferences: () => string[] }>;
    onOptimisticSubmit?: (formData: FormValues) => (() => void) | void;
};

type AlvaFormReturn<K extends keyof AlvaEvents, FormValues extends object> =
    UseLiveFormReturn<FormValues> & {
        submit: () => Promise<AlvaEvents[K]["output"]>;
    };

function clearFormErrors(errors: Record<string, string[]>) {
    for (const key of Object.keys(errors)) {
        delete errors[key];
    }
}

export function useAlvaForm<
    K extends keyof AlvaEvents,
    FormValues extends object = AlvaEvents[K]["input"],
>(
    submitEvent: K,
    options: AlvaFormOptions<FormValues, keyof AlvaEvents>,
): AlvaFormReturn<K, FormValues> {
    const pseudoForm = reactive({
        name: submitEvent as string,
        values: JSON.parse(JSON.stringify(options.initialValues)),
        errors: {} as Record<string, string[]>,
        valid: true,
    }) as Form<FormValues>;

    const liveForm = useLiveForm(pseudoForm, {
        submitEvent: submitEvent as string,
        changeEvent: (options.validateEvent as string) || null,
        debounceInMiliseconds: options.debounceMs || 300,
        prepareData: (data: any) => {
            if (options.uploads) {
                for (const [key, upload] of Object.entries(options.uploads)) {
                    data[key] = upload.getFileReferences();
                }
            }
            return data;
        }
    });

    const originalSubmit = liveForm.submit;

    const submit = async (): Promise<AlvaEvents[K]["output"]> => {
        const rollbackFn = options.onOptimisticSubmit?.(pseudoForm.values);
        let result: any;

        try {
            result = await originalSubmit();
        } catch (e: any) {
            result = { ok: false, error: { type: "unknown", message: e.message || String(e) } };
        }

        if (!result || !result.ok) {
            if (rollbackFn) rollbackFn();

            if (result?.error?.fields) {
                clearFormErrors(pseudoForm.errors);
                Object.assign(pseudoForm.errors, result.error.fields);
            }
        } else {
            clearFormErrors(pseudoForm.errors);
        }

        return result;
    };

    return {
        ...liveForm,
        submit,
    } as AlvaFormReturn<K, FormValues>;
}
