// This file is auto-generated by Alva.
// Do not edit manually.

import { ref, watch, type Ref, type WatchSource } from "vue";
import { useLiveVue } from "live_vue";
import type { AlvaEvents } from "../events";

export interface AlvaQueryOptions {
    debounceMs?: number;
}

export interface AlvaQueryReturn<Output> {
    data: Ref<Output | null>;
    loading: Ref<boolean>;
    refetch: () => Promise<void>;
}

export function useAlvaQuery<
    K extends keyof AlvaEvents,
    Input = AlvaEvents[K]["input"],
    Output = Extract<AlvaEvents[K]["output"], { ok: true }> extends { data: infer D } ? D : never
>(
    queryEvent: K,
    inputGetter: WatchSource<Input>,
    options: AlvaQueryOptions = {}
): AlvaQueryReturn<Output> {
    const live = useLiveVue();
    const data = ref<Output | null>(null) as Ref<Output | null>;
    const loading = ref(false);

    const debounceMs = options.debounceMs ?? 0;
    let timeoutId: any;
    let currentRequestId = 0;

    const fetchQuery = async (currentInput: Input) => {
        const requestId = ++currentRequestId;
        
        return new Promise<void>((resolve) => {
            live.pushEvent(queryEvent as string, currentInput as any, (reply: any) => {
                if (requestId !== currentRequestId) return resolve();
                
                loading.value = false;
                if (reply.ok) {
                    data.value = reply.data;
                }
                resolve();
            });
        });
    };

    const debouncedFetch = (currentInput: Input) => {
        loading.value = true;
        if (debounceMs > 0) {
            clearTimeout(timeoutId);
            timeoutId = setTimeout(() => {
                fetchQuery(currentInput);
            }, debounceMs);
        } else {
            fetchQuery(currentInput);
        }
    };

    watch(inputGetter, (newInput) => {
        debouncedFetch(newInput);
    }, { deep: true, immediate: true });

    return {
        data,
        loading,
        refetch: async () => {
            const currentInput = typeof inputGetter === "function" ? (inputGetter as any)() : (inputGetter as any).value;
            loading.value = true;
            await fetchQuery(currentInput);
        }
    };
}
