// This file is auto-generated by Alva.
// Do not edit manually.

import { useLiveVue, useLiveEvent } from "live_vue";
import { ref, computed, onUnmounted } from "vue";
import { useAlvaForm, type AlvaFormOptions } from "./useAlvaForm";
import { useAlvaQuery } from "./useAlvaQuery";
import { useAlvaUpload } from "./useAlvaUpload";
import type { AlvaEvents } from "../events";
import type { AlvaSignals } from "../signals";
import type { AlvaError } from "../types";

export type { AlvaError };

export interface AlvaConfig {
    onError?: (error: AlvaError, event: string) => void;
    onSuccess?: (data: unknown, event: string) => void;
}

export function useAlva(config?: AlvaConfig) {
    let live: any = null;
    try {
        live = useLiveVue();
    } catch (_e) {
        live = null;
    }

    const safePushEvent = (event: string, payload: any, callback: any) => {
        if (live && typeof live.pushEvent === "function") {
            return live.pushEvent(event, payload, callback);
        }
        callback?.({ ok: false, error: { type: "unmounted", message: "LiveVue context not available" } });
    };

    return {
    catalog: {
        adjust_stock: (payload: AlvaEvents["catalog.adjust_stock"]["input"]): Promise<AlvaEvents["catalog.adjust_stock"]["output"]> => {
            return new Promise((resolve) => {
                const startTime = performance.now();
                safePushEvent("catalog.adjust_stock", payload, (reply: AlvaEvents["catalog.adjust_stock"]["output"]) => {
                    const durationMs = Math.round(performance.now() - startTime);
                    if (typeof window !== "undefined" && (window as any).__ALVA_RECORD_TELEMETRY__) {
                        (window as any).__ALVA_RECORD_TELEMETRY__("catalog.adjust_stock", durationMs, reply?.ok);
                    }
                    if (reply?.ok) {
                        config?.onSuccess?.(reply.data, "catalog.adjust_stock");
                    } else {
                        config?.onError?.(reply?.error, "catalog.adjust_stock");
                    }
                    resolve(reply);
                });
            });
        },
        use_adjust_stock_form: (
            options: Extract<AlvaEvents["catalog.adjust_stock"]["input"], object> extends never ? never : AlvaFormOptions<Extract<AlvaEvents["catalog.adjust_stock"]["input"], object>, keyof AlvaEvents>
        ) => {
            return useAlvaForm("catalog.adjust_stock", options);
        },
        use_adjust_stock_upload: (options?: import("./useAlvaUpload").AlvaUploadOptions) => {
            return useAlvaUpload("catalog.adjust_stock", options);
        }
,
        get_product: (payload: AlvaEvents["catalog.get_product"]["input"]): Promise<AlvaEvents["catalog.get_product"]["output"]> => {
            return new Promise((resolve) => {
                const startTime = performance.now();
                safePushEvent("catalog.get_product", payload, (reply: AlvaEvents["catalog.get_product"]["output"]) => {
                    const durationMs = Math.round(performance.now() - startTime);
                    if (typeof window !== "undefined" && (window as any).__ALVA_RECORD_TELEMETRY__) {
                        (window as any).__ALVA_RECORD_TELEMETRY__("catalog.get_product", durationMs, reply?.ok);
                    }
                    if (reply?.ok) {
                        config?.onSuccess?.(reply.data, "catalog.get_product");
                    } else {
                        config?.onError?.(reply?.error, "catalog.get_product");
                    }
                    resolve(reply);
                });
            });
        },
        use_get_product_form: (
            options: Extract<AlvaEvents["catalog.get_product"]["input"], object> extends never ? never : AlvaFormOptions<Extract<AlvaEvents["catalog.get_product"]["input"], object>, keyof AlvaEvents>
        ) => {
            return useAlvaForm("catalog.get_product", options);
        },
        use_get_product_upload: (options?: import("./useAlvaUpload").AlvaUploadOptions) => {
            return useAlvaUpload("catalog.get_product", options);
        },
        use_get_product_query: (
            inputGetter: () => AlvaEvents["catalog.get_product"]["input"],
            options?: import("./useAlvaQuery").AlvaQueryOptions
        ) => {
            return useAlvaQuery("catalog.get_product", inputGetter, options);
        },
        use_get_product_by_id: (
            idGetter: import("vue").WatchSource<string | null | undefined>,
            options?: import("./useAlvaQuery").AlvaQueryOptions
        ) => {
            const inputGetter = () => {
                const id = typeof idGetter === "function" ? idGetter() : (idGetter as any)?.value;
                return id ? ({ id: id } as any) : null;
            };
            return useAlvaQuery("catalog.get_product", inputGetter, options);
        }


,
        list_products: (payload: AlvaEvents["catalog.list_products"]["input"]): Promise<AlvaEvents["catalog.list_products"]["output"]> => {
            return new Promise((resolve) => {
                const startTime = performance.now();
                safePushEvent("catalog.list_products", payload, (reply: AlvaEvents["catalog.list_products"]["output"]) => {
                    const durationMs = Math.round(performance.now() - startTime);
                    if (typeof window !== "undefined" && (window as any).__ALVA_RECORD_TELEMETRY__) {
                        (window as any).__ALVA_RECORD_TELEMETRY__("catalog.list_products", durationMs, reply?.ok);
                    }
                    if (reply?.ok) {
                        config?.onSuccess?.(reply.data, "catalog.list_products");
                    } else {
                        config?.onError?.(reply?.error, "catalog.list_products");
                    }
                    resolve(reply);
                });
            });
        },
        use_list_products_form: (
            options: Extract<AlvaEvents["catalog.list_products"]["input"], object> extends never ? never : AlvaFormOptions<Extract<AlvaEvents["catalog.list_products"]["input"], object>, keyof AlvaEvents>
        ) => {
            return useAlvaForm("catalog.list_products", options);
        },
        use_list_products_upload: (options?: import("./useAlvaUpload").AlvaUploadOptions) => {
            return useAlvaUpload("catalog.list_products", options);
        },
        use_list_products_query: (
            inputGetter: () => AlvaEvents["catalog.list_products"]["input"],
            options?: import("./useAlvaQuery").AlvaQueryOptions
        ) => {
            return useAlvaQuery("catalog.list_products", inputGetter, options);
        },
        use_list_products_by_id: (
            idGetter: import("vue").WatchSource<string | null | undefined>,
            options?: import("./useAlvaQuery").AlvaQueryOptions
        ) => {
            const inputGetter = () => {
                const id = typeof idGetter === "function" ? idGetter() : (idGetter as any)?.value;
                return id ? ({ id: id } as any) : null;
            };
            return useAlvaQuery("catalog.list_products", inputGetter, options);
        }


,
        upload_media: (payload: AlvaEvents["catalog.upload_media"]["input"]): Promise<AlvaEvents["catalog.upload_media"]["output"]> => {
            return new Promise((resolve) => {
                const startTime = performance.now();
                safePushEvent("catalog.upload_media", payload, (reply: AlvaEvents["catalog.upload_media"]["output"]) => {
                    const durationMs = Math.round(performance.now() - startTime);
                    if (typeof window !== "undefined" && (window as any).__ALVA_RECORD_TELEMETRY__) {
                        (window as any).__ALVA_RECORD_TELEMETRY__("catalog.upload_media", durationMs, reply?.ok);
                    }
                    if (reply?.ok) {
                        config?.onSuccess?.(reply.data, "catalog.upload_media");
                    } else {
                        config?.onError?.(reply?.error, "catalog.upload_media");
                    }
                    resolve(reply);
                });
            });
        },
        use_upload_media_form: (
            options: Extract<AlvaEvents["catalog.upload_media"]["input"], object> extends never ? never : AlvaFormOptions<Extract<AlvaEvents["catalog.upload_media"]["input"], object>, keyof AlvaEvents>
        ) => {
            return useAlvaForm("catalog.upload_media", options);
        },
        use_upload_media_upload: (options?: import("./useAlvaUpload").AlvaUploadOptions) => {
            return useAlvaUpload("catalog.upload_media", options);
        }

    }
,
    demo_chat: {
        list_messages: (payload: AlvaEvents["demo_chat.list_messages"]["input"]): Promise<AlvaEvents["demo_chat.list_messages"]["output"]> => {
            return new Promise((resolve) => {
                const startTime = performance.now();
                safePushEvent("demo_chat.list_messages", payload, (reply: AlvaEvents["demo_chat.list_messages"]["output"]) => {
                    const durationMs = Math.round(performance.now() - startTime);
                    if (typeof window !== "undefined" && (window as any).__ALVA_RECORD_TELEMETRY__) {
                        (window as any).__ALVA_RECORD_TELEMETRY__("demo_chat.list_messages", durationMs, reply?.ok);
                    }
                    if (reply?.ok) {
                        config?.onSuccess?.(reply.data, "demo_chat.list_messages");
                    } else {
                        config?.onError?.(reply?.error, "demo_chat.list_messages");
                    }
                    resolve(reply);
                });
            });
        },
        use_list_messages_form: (
            options: Extract<AlvaEvents["demo_chat.list_messages"]["input"], object> extends never ? never : AlvaFormOptions<Extract<AlvaEvents["demo_chat.list_messages"]["input"], object>, keyof AlvaEvents>
        ) => {
            return useAlvaForm("demo_chat.list_messages", options);
        },
        use_list_messages_upload: (options?: import("./useAlvaUpload").AlvaUploadOptions) => {
            return useAlvaUpload("demo_chat.list_messages", options);
        },
        use_list_messages_query: (
            inputGetter: () => AlvaEvents["demo_chat.list_messages"]["input"],
            options?: import("./useAlvaQuery").AlvaQueryOptions
        ) => {
            return useAlvaQuery("demo_chat.list_messages", inputGetter, options);
        },
        use_list_messages_by_id: (
            idGetter: import("vue").WatchSource<string | null | undefined>,
            options?: import("./useAlvaQuery").AlvaQueryOptions
        ) => {
            const inputGetter = () => {
                const id = typeof idGetter === "function" ? idGetter() : (idGetter as any)?.value;
                return id ? ({ id: id } as any) : null;
            };
            return useAlvaQuery("demo_chat.list_messages", inputGetter, options);
        }


,
        send_message: (payload: AlvaEvents["demo_chat.send_message"]["input"]): Promise<AlvaEvents["demo_chat.send_message"]["output"]> => {
            return new Promise((resolve) => {
                const startTime = performance.now();
                safePushEvent("demo_chat.send_message", payload, (reply: AlvaEvents["demo_chat.send_message"]["output"]) => {
                    const durationMs = Math.round(performance.now() - startTime);
                    if (typeof window !== "undefined" && (window as any).__ALVA_RECORD_TELEMETRY__) {
                        (window as any).__ALVA_RECORD_TELEMETRY__("demo_chat.send_message", durationMs, reply?.ok);
                    }
                    if (reply?.ok) {
                        config?.onSuccess?.(reply.data, "demo_chat.send_message");
                    } else {
                        config?.onError?.(reply?.error, "demo_chat.send_message");
                    }
                    resolve(reply);
                });
            });
        },
        use_send_message_form: (
            options: Extract<AlvaEvents["demo_chat.send_message"]["input"], object> extends never ? never : AlvaFormOptions<Extract<AlvaEvents["demo_chat.send_message"]["input"], object>, keyof AlvaEvents>
        ) => {
            return useAlvaForm("demo_chat.send_message", options);
        },
        use_send_message_upload: (options?: import("./useAlvaUpload").AlvaUploadOptions) => {
            return useAlvaUpload("demo_chat.send_message", options);
        }

    }
,
    demo_feed: {
        list_entries: (payload: AlvaEvents["demo_feed.list_entries"]["input"]): Promise<AlvaEvents["demo_feed.list_entries"]["output"]> => {
            return new Promise((resolve) => {
                const startTime = performance.now();
                safePushEvent("demo_feed.list_entries", payload, (reply: AlvaEvents["demo_feed.list_entries"]["output"]) => {
                    const durationMs = Math.round(performance.now() - startTime);
                    if (typeof window !== "undefined" && (window as any).__ALVA_RECORD_TELEMETRY__) {
                        (window as any).__ALVA_RECORD_TELEMETRY__("demo_feed.list_entries", durationMs, reply?.ok);
                    }
                    if (reply?.ok) {
                        config?.onSuccess?.(reply.data, "demo_feed.list_entries");
                    } else {
                        config?.onError?.(reply?.error, "demo_feed.list_entries");
                    }
                    resolve(reply);
                });
            });
        },
        use_list_entries_form: (
            options: Extract<AlvaEvents["demo_feed.list_entries"]["input"], object> extends never ? never : AlvaFormOptions<Extract<AlvaEvents["demo_feed.list_entries"]["input"], object>, keyof AlvaEvents>
        ) => {
            return useAlvaForm("demo_feed.list_entries", options);
        },
        use_list_entries_upload: (options?: import("./useAlvaUpload").AlvaUploadOptions) => {
            return useAlvaUpload("demo_feed.list_entries", options);
        },
        use_list_entries_query: (
            inputGetter: () => AlvaEvents["demo_feed.list_entries"]["input"],
            options?: import("./useAlvaQuery").AlvaQueryOptions
        ) => {
            return useAlvaQuery("demo_feed.list_entries", inputGetter, options);
        },
        use_list_entries_by_id: (
            idGetter: import("vue").WatchSource<string | null | undefined>,
            options?: import("./useAlvaQuery").AlvaQueryOptions
        ) => {
            const inputGetter = () => {
                const id = typeof idGetter === "function" ? idGetter() : (idGetter as any)?.value;
                return id ? ({ id: id } as any) : null;
            };
            return useAlvaQuery("demo_feed.list_entries", inputGetter, options);
        }



    }
,
    demo_notifications: {
        send: (payload: AlvaEvents["demo_notifications.send"]["input"]): Promise<AlvaEvents["demo_notifications.send"]["output"]> => {
            return new Promise((resolve) => {
                const startTime = performance.now();
                safePushEvent("demo_notifications.send", payload, (reply: AlvaEvents["demo_notifications.send"]["output"]) => {
                    const durationMs = Math.round(performance.now() - startTime);
                    if (typeof window !== "undefined" && (window as any).__ALVA_RECORD_TELEMETRY__) {
                        (window as any).__ALVA_RECORD_TELEMETRY__("demo_notifications.send", durationMs, reply?.ok);
                    }
                    if (reply?.ok) {
                        config?.onSuccess?.(reply.data, "demo_notifications.send");
                    } else {
                        config?.onError?.(reply?.error, "demo_notifications.send");
                    }
                    resolve(reply);
                });
            });
        },
        use_send_form: (
            options: Extract<AlvaEvents["demo_notifications.send"]["input"], object> extends never ? never : AlvaFormOptions<Extract<AlvaEvents["demo_notifications.send"]["input"], object>, keyof AlvaEvents>
        ) => {
            return useAlvaForm("demo_notifications.send", options);
        },
        use_send_upload: (options?: import("./useAlvaUpload").AlvaUploadOptions) => {
            return useAlvaUpload("demo_notifications.send", options);
        }
,
        on_sent: (
            input: AlvaSignals["demo_notifications.sent"] extends { input: infer I } ? I : Record<string, never>,
            callback: (payload: AlvaSignals["demo_notifications.sent"]["payload"]) => void
        ) => {
            if (live) live.pushEvent("alva:subscribe_signal", { name: "demo_notifications.sent", input }, () => {});
            useLiveEvent("demo_notifications.sent", callback);
            onUnmounted(() => {
                if (live) live.pushEvent("alva:unsubscribe_signal", { name: "demo_notifications.sent", input }, () => {});
            });
        },
        use_sent_state: (
            input: AlvaSignals["demo_notifications.sent"] extends { input: infer I } ? I : Record<string, never> = {} as any
        ) => {
            const data = ref<AlvaSignals["demo_notifications.sent"]["payload"][]>([]);
            const latest = ref<AlvaSignals["demo_notifications.sent"]["payload"] | null>(null);
            const count = computed(() => data.value.length);
            const clear = () => { data.value = []; latest.value = null; };

            if (live) live.pushEvent("alva:subscribe_signal", { name: "demo_notifications.sent", input }, () => {});
            useLiveEvent("demo_notifications.sent", (payload: any) => {
                latest.value = payload;
                data.value.unshift(payload);
            });
            onUnmounted(() => {
                if (live) live.pushEvent("alva:unsubscribe_signal", { name: "demo_notifications.sent", input }, () => {});
            });

            return { data, latest, count, clear };
        }

    }
,
    sales: {
        begin_processing: (payload: AlvaEvents["sales.begin_processing"]["input"]): Promise<AlvaEvents["sales.begin_processing"]["output"]> => {
            return new Promise((resolve) => {
                const startTime = performance.now();
                safePushEvent("sales.begin_processing", payload, (reply: AlvaEvents["sales.begin_processing"]["output"]) => {
                    const durationMs = Math.round(performance.now() - startTime);
                    if (typeof window !== "undefined" && (window as any).__ALVA_RECORD_TELEMETRY__) {
                        (window as any).__ALVA_RECORD_TELEMETRY__("sales.begin_processing", durationMs, reply?.ok);
                    }
                    if (reply?.ok) {
                        config?.onSuccess?.(reply.data, "sales.begin_processing");
                    } else {
                        config?.onError?.(reply?.error, "sales.begin_processing");
                    }
                    resolve(reply);
                });
            });
        },
        use_begin_processing_form: (
            options: Extract<AlvaEvents["sales.begin_processing"]["input"], object> extends never ? never : AlvaFormOptions<Extract<AlvaEvents["sales.begin_processing"]["input"], object>, keyof AlvaEvents>
        ) => {
            return useAlvaForm("sales.begin_processing", options);
        },
        use_begin_processing_upload: (options?: import("./useAlvaUpload").AlvaUploadOptions) => {
            return useAlvaUpload("sales.begin_processing", options);
        }
,
        create_order: (payload: AlvaEvents["sales.create_order"]["input"]): Promise<AlvaEvents["sales.create_order"]["output"]> => {
            return new Promise((resolve) => {
                const startTime = performance.now();
                safePushEvent("sales.create_order", payload, (reply: AlvaEvents["sales.create_order"]["output"]) => {
                    const durationMs = Math.round(performance.now() - startTime);
                    if (typeof window !== "undefined" && (window as any).__ALVA_RECORD_TELEMETRY__) {
                        (window as any).__ALVA_RECORD_TELEMETRY__("sales.create_order", durationMs, reply?.ok);
                    }
                    if (reply?.ok) {
                        config?.onSuccess?.(reply.data, "sales.create_order");
                    } else {
                        config?.onError?.(reply?.error, "sales.create_order");
                    }
                    resolve(reply);
                });
            });
        },
        use_create_order_form: (
            options: Extract<AlvaEvents["sales.create_order"]["input"], object> extends never ? never : AlvaFormOptions<Extract<AlvaEvents["sales.create_order"]["input"], object>, keyof AlvaEvents>
        ) => {
            return useAlvaForm("sales.create_order", options);
        },
        use_create_order_upload: (options?: import("./useAlvaUpload").AlvaUploadOptions) => {
            return useAlvaUpload("sales.create_order", options);
        }
,
        fulfill: (payload: AlvaEvents["sales.fulfill"]["input"]): Promise<AlvaEvents["sales.fulfill"]["output"]> => {
            return new Promise((resolve) => {
                const startTime = performance.now();
                safePushEvent("sales.fulfill", payload, (reply: AlvaEvents["sales.fulfill"]["output"]) => {
                    const durationMs = Math.round(performance.now() - startTime);
                    if (typeof window !== "undefined" && (window as any).__ALVA_RECORD_TELEMETRY__) {
                        (window as any).__ALVA_RECORD_TELEMETRY__("sales.fulfill", durationMs, reply?.ok);
                    }
                    if (reply?.ok) {
                        config?.onSuccess?.(reply.data, "sales.fulfill");
                    } else {
                        config?.onError?.(reply?.error, "sales.fulfill");
                    }
                    resolve(reply);
                });
            });
        },
        use_fulfill_form: (
            options: Extract<AlvaEvents["sales.fulfill"]["input"], object> extends never ? never : AlvaFormOptions<Extract<AlvaEvents["sales.fulfill"]["input"], object>, keyof AlvaEvents>
        ) => {
            return useAlvaForm("sales.fulfill", options);
        },
        use_fulfill_upload: (options?: import("./useAlvaUpload").AlvaUploadOptions) => {
            return useAlvaUpload("sales.fulfill", options);
        }
,
        list_orders: (payload: AlvaEvents["sales.list_orders"]["input"]): Promise<AlvaEvents["sales.list_orders"]["output"]> => {
            return new Promise((resolve) => {
                const startTime = performance.now();
                safePushEvent("sales.list_orders", payload, (reply: AlvaEvents["sales.list_orders"]["output"]) => {
                    const durationMs = Math.round(performance.now() - startTime);
                    if (typeof window !== "undefined" && (window as any).__ALVA_RECORD_TELEMETRY__) {
                        (window as any).__ALVA_RECORD_TELEMETRY__("sales.list_orders", durationMs, reply?.ok);
                    }
                    if (reply?.ok) {
                        config?.onSuccess?.(reply.data, "sales.list_orders");
                    } else {
                        config?.onError?.(reply?.error, "sales.list_orders");
                    }
                    resolve(reply);
                });
            });
        },
        use_list_orders_form: (
            options: Extract<AlvaEvents["sales.list_orders"]["input"], object> extends never ? never : AlvaFormOptions<Extract<AlvaEvents["sales.list_orders"]["input"], object>, keyof AlvaEvents>
        ) => {
            return useAlvaForm("sales.list_orders", options);
        },
        use_list_orders_upload: (options?: import("./useAlvaUpload").AlvaUploadOptions) => {
            return useAlvaUpload("sales.list_orders", options);
        },
        use_list_orders_query: (
            inputGetter: () => AlvaEvents["sales.list_orders"]["input"],
            options?: import("./useAlvaQuery").AlvaQueryOptions
        ) => {
            return useAlvaQuery("sales.list_orders", inputGetter, options);
        },
        use_list_orders_by_id: (
            idGetter: import("vue").WatchSource<string | null | undefined>,
            options?: import("./useAlvaQuery").AlvaQueryOptions
        ) => {
            const inputGetter = () => {
                const id = typeof idGetter === "function" ? idGetter() : (idGetter as any)?.value;
                return id ? ({ id: id } as any) : null;
            };
            return useAlvaQuery("sales.list_orders", inputGetter, options);
        }



    }
,
    support: {
        create: (payload: AlvaEvents["support.create"]["input"]): Promise<AlvaEvents["support.create"]["output"]> => {
            return new Promise((resolve) => {
                const startTime = performance.now();
                safePushEvent("support.create", payload, (reply: AlvaEvents["support.create"]["output"]) => {
                    const durationMs = Math.round(performance.now() - startTime);
                    if (typeof window !== "undefined" && (window as any).__ALVA_RECORD_TELEMETRY__) {
                        (window as any).__ALVA_RECORD_TELEMETRY__("support.create", durationMs, reply?.ok);
                    }
                    if (reply?.ok) {
                        config?.onSuccess?.(reply.data, "support.create");
                    } else {
                        config?.onError?.(reply?.error, "support.create");
                    }
                    resolve(reply);
                });
            });
        },
        use_create_form: (
            options: Extract<AlvaEvents["support.create"]["input"], object> extends never ? never : AlvaFormOptions<Extract<AlvaEvents["support.create"]["input"], object>, keyof AlvaEvents>
        ) => {
            return useAlvaForm("support.create", options);
        },
        use_create_upload: (options?: import("./useAlvaUpload").AlvaUploadOptions) => {
            return useAlvaUpload("support.create", options);
        }
,
        get_conversation: (payload: AlvaEvents["support.get_conversation"]["input"]): Promise<AlvaEvents["support.get_conversation"]["output"]> => {
            return new Promise((resolve) => {
                const startTime = performance.now();
                safePushEvent("support.get_conversation", payload, (reply: AlvaEvents["support.get_conversation"]["output"]) => {
                    const durationMs = Math.round(performance.now() - startTime);
                    if (typeof window !== "undefined" && (window as any).__ALVA_RECORD_TELEMETRY__) {
                        (window as any).__ALVA_RECORD_TELEMETRY__("support.get_conversation", durationMs, reply?.ok);
                    }
                    if (reply?.ok) {
                        config?.onSuccess?.(reply.data, "support.get_conversation");
                    } else {
                        config?.onError?.(reply?.error, "support.get_conversation");
                    }
                    resolve(reply);
                });
            });
        },
        use_get_conversation_form: (
            options: Extract<AlvaEvents["support.get_conversation"]["input"], object> extends never ? never : AlvaFormOptions<Extract<AlvaEvents["support.get_conversation"]["input"], object>, keyof AlvaEvents>
        ) => {
            return useAlvaForm("support.get_conversation", options);
        },
        use_get_conversation_upload: (options?: import("./useAlvaUpload").AlvaUploadOptions) => {
            return useAlvaUpload("support.get_conversation", options);
        },
        use_get_conversation_query: (
            inputGetter: () => AlvaEvents["support.get_conversation"]["input"],
            options?: import("./useAlvaQuery").AlvaQueryOptions
        ) => {
            return useAlvaQuery("support.get_conversation", inputGetter, options);
        },
        use_get_conversation_by_id: (
            idGetter: import("vue").WatchSource<string | null | undefined>,
            options?: import("./useAlvaQuery").AlvaQueryOptions
        ) => {
            const inputGetter = () => {
                const id = typeof idGetter === "function" ? idGetter() : (idGetter as any)?.value;
                return id ? ({ id: id } as any) : null;
            };
            return useAlvaQuery("support.get_conversation", inputGetter, options);
        }


,
        list_conversations: (payload: AlvaEvents["support.list_conversations"]["input"]): Promise<AlvaEvents["support.list_conversations"]["output"]> => {
            return new Promise((resolve) => {
                const startTime = performance.now();
                safePushEvent("support.list_conversations", payload, (reply: AlvaEvents["support.list_conversations"]["output"]) => {
                    const durationMs = Math.round(performance.now() - startTime);
                    if (typeof window !== "undefined" && (window as any).__ALVA_RECORD_TELEMETRY__) {
                        (window as any).__ALVA_RECORD_TELEMETRY__("support.list_conversations", durationMs, reply?.ok);
                    }
                    if (reply?.ok) {
                        config?.onSuccess?.(reply.data, "support.list_conversations");
                    } else {
                        config?.onError?.(reply?.error, "support.list_conversations");
                    }
                    resolve(reply);
                });
            });
        },
        use_list_conversations_form: (
            options: Extract<AlvaEvents["support.list_conversations"]["input"], object> extends never ? never : AlvaFormOptions<Extract<AlvaEvents["support.list_conversations"]["input"], object>, keyof AlvaEvents>
        ) => {
            return useAlvaForm("support.list_conversations", options);
        },
        use_list_conversations_upload: (options?: import("./useAlvaUpload").AlvaUploadOptions) => {
            return useAlvaUpload("support.list_conversations", options);
        },
        use_list_conversations_query: (
            inputGetter: () => AlvaEvents["support.list_conversations"]["input"],
            options?: import("./useAlvaQuery").AlvaQueryOptions
        ) => {
            return useAlvaQuery("support.list_conversations", inputGetter, options);
        },
        use_list_conversations_by_id: (
            idGetter: import("vue").WatchSource<string | null | undefined>,
            options?: import("./useAlvaQuery").AlvaQueryOptions
        ) => {
            const inputGetter = () => {
                const id = typeof idGetter === "function" ? idGetter() : (idGetter as any)?.value;
                return id ? ({ id: id } as any) : null;
            };
            return useAlvaQuery("support.list_conversations", inputGetter, options);
        }


,
        list_messages: (payload: AlvaEvents["support.list_messages"]["input"]): Promise<AlvaEvents["support.list_messages"]["output"]> => {
            return new Promise((resolve) => {
                const startTime = performance.now();
                safePushEvent("support.list_messages", payload, (reply: AlvaEvents["support.list_messages"]["output"]) => {
                    const durationMs = Math.round(performance.now() - startTime);
                    if (typeof window !== "undefined" && (window as any).__ALVA_RECORD_TELEMETRY__) {
                        (window as any).__ALVA_RECORD_TELEMETRY__("support.list_messages", durationMs, reply?.ok);
                    }
                    if (reply?.ok) {
                        config?.onSuccess?.(reply.data, "support.list_messages");
                    } else {
                        config?.onError?.(reply?.error, "support.list_messages");
                    }
                    resolve(reply);
                });
            });
        },
        use_list_messages_form: (
            options: Extract<AlvaEvents["support.list_messages"]["input"], object> extends never ? never : AlvaFormOptions<Extract<AlvaEvents["support.list_messages"]["input"], object>, keyof AlvaEvents>
        ) => {
            return useAlvaForm("support.list_messages", options);
        },
        use_list_messages_upload: (options?: import("./useAlvaUpload").AlvaUploadOptions) => {
            return useAlvaUpload("support.list_messages", options);
        },
        use_list_messages_query: (
            inputGetter: () => AlvaEvents["support.list_messages"]["input"],
            options?: import("./useAlvaQuery").AlvaQueryOptions
        ) => {
            return useAlvaQuery("support.list_messages", inputGetter, options);
        },
        use_list_messages_by_id: (
            idGetter: import("vue").WatchSource<string | null | undefined>,
            options?: import("./useAlvaQuery").AlvaQueryOptions
        ) => {
            const inputGetter = () => {
                const id = typeof idGetter === "function" ? idGetter() : (idGetter as any)?.value;
                return id ? ({ id: id } as any) : null;
            };
            return useAlvaQuery("support.list_messages", inputGetter, options);
        }


,
        send_message: (payload: AlvaEvents["support.send_message"]["input"]): Promise<AlvaEvents["support.send_message"]["output"]> => {
            return new Promise((resolve) => {
                const startTime = performance.now();
                safePushEvent("support.send_message", payload, (reply: AlvaEvents["support.send_message"]["output"]) => {
                    const durationMs = Math.round(performance.now() - startTime);
                    if (typeof window !== "undefined" && (window as any).__ALVA_RECORD_TELEMETRY__) {
                        (window as any).__ALVA_RECORD_TELEMETRY__("support.send_message", durationMs, reply?.ok);
                    }
                    if (reply?.ok) {
                        config?.onSuccess?.(reply.data, "support.send_message");
                    } else {
                        config?.onError?.(reply?.error, "support.send_message");
                    }
                    resolve(reply);
                });
            });
        },
        use_send_message_form: (
            options: Extract<AlvaEvents["support.send_message"]["input"], object> extends never ? never : AlvaFormOptions<Extract<AlvaEvents["support.send_message"]["input"], object>, keyof AlvaEvents>
        ) => {
            return useAlvaForm("support.send_message", options);
        },
        use_send_message_upload: (options?: import("./useAlvaUpload").AlvaUploadOptions) => {
            return useAlvaUpload("support.send_message", options);
        }

    }
,
      use_upload: (name: string, options?: import("./useAlvaUpload").AlvaUploadOptions) => {
          return useAlvaUpload(name, options);
      }

    };
}
