// This file is auto-generated by Alva.
// Do not edit manually.

import { computed, type ComputedRef } from "vue";
import { useLiveVue } from "live_vue";

export function useAlvaAssigns<T extends Record<string, any> = Record<string, any>>(): ComputedRef<T> {
    const live = useLiveVue();
    return computed(() => {
        const props = (live.vue?.props || {}) as Record<string, any>;
        return (props.assigns || props) as T;
    });
}
