// This file is auto-generated by Alva.
// Do not edit manually.

import { computed, ref, watch } from "vue";
import { useLiveUpload, useLiveVue } from "live_vue";

export type UploadEntry = {
    ref: string;
    client_name?: string;
    client_size?: number;
    client_type?: string;
    name?: string;
    size?: number;
    type?: string;
    progress: number;
    error?: string;
};

export type AlvaUploadOptions = {
    maxFiles?: number;
    maxSize?: number;
};

export type AlvaUploadDispatchContext = {
    files: UploadEntry[];
    references: string[];
    primaryReference: string;
};

const ALVA_UPLOAD_CHANGE_EVENT = "alva.validate_upload";
const ALVA_UPLOAD_SUBMIT_EVENT = "alva.save_upload";

type UploadConfigShape = {
    ref: string;
    name: string;
    accept: string | false;
    max_entries: number;
    auto_upload: boolean;
    entries: UploadEntry[];
    errors: unknown[];
};

export function useAlvaUpload(name: string, options?: AlvaUploadOptions) {
    const live = useLiveVue();
    const uploadProps = live.vue?.props as Record<string, unknown> | null | undefined;

    const getUploadConfig = (): UploadConfigShape | null => {
        const directConfig = uploadProps?.[name];
        if (isUploadConfig(directConfig)) return directConfig;

        const nested = uploadProps?.uploads;
        if (nested && typeof nested === "object" && !Array.isArray(nested)) {
            const nestedConfig = (nested as Record<string, unknown>)[name];
            if (isUploadConfig(nestedConfig)) return nestedConfig;
        }
        return null;
    };

    const config = getUploadConfig();

    if (!config) {
        return missingUpload(name);
    }

    const upload = useLiveUpload(getUploadConfig, {
        changeEvent: ALVA_UPLOAD_CHANGE_EVENT,
        submitEvent: ALVA_UPLOAD_SUBMIT_EVENT,
        ...(options || {}),
    }) as any;

    const files = computed<UploadEntry[]>(() => upload.entries?.value || []);
    const errors = computed(() => upload.errors?.value || []);

    const progress = computed(() => {
        if (files.value.length === 0) return 0;
        let totalSize = 0;
        let totalUploaded = 0;
        for (const file of files.value) {
            const size = file.client_size ?? file.size ?? 0;
            totalSize += size;
            totalUploaded += size * ((file.progress || 0) / 100);
        }
        return totalSize === 0 ? 0 : Math.round((totalUploaded / totalSize) * 100);
    });

    const enforceLimits = () => {
        if (!options || !upload.cancel) return;
        if (options.maxFiles && files.value.length > options.maxFiles) {
            files.value.slice(options.maxFiles).forEach((f) => upload.cancel(f.ref));
        }
        if (options.maxSize) {
            files.value.forEach((f) => {
                const size = f.client_size ?? f.size ?? 0;
                if (size > options.maxSize!) upload.cancel(f.ref);
            });
        }
    };

    watch(files, enforceLimits, { deep: true, immediate: true });

    const getFileReferences = () => files.value.map((f) => f.ref);

    const waitForCompletion = (): Promise<AlvaUploadDispatchContext> => {
        return new Promise((resolve, reject) => {
            let settled = false;
            let stop: (() => void) | undefined;

            const settle = (cb: () => void) => {
                if (settled) return;
                settled = true;
                stop?.();
                cb();
            };

            const tryComplete = () => {
                if (files.value.length === 0 || progress.value !== 100) return;
                const refs = getFileReferences();
                const primary = refs[0];
                if (!primary) {
                    settle(() => reject(new Error("No uploaded file reference was produced.")));
                    return;
                }
                settle(() => resolve({ files: [...files.value], references: refs, primaryReference: primary }));
            };

            tryComplete();
            if (settled) return;
            stop = watch([files, progress], tryComplete, { deep: true });
        });
    };

    const dispatch = async <T>(
        submit: (ctx: AlvaUploadDispatchContext) => Promise<T>,
        opts: { clear?: boolean } = {},
    ) => {
        try {
            const ctx = await waitForCompletion();
            return await submit(ctx);
        } finally {
            if (opts.clear !== false) upload.clear?.();
        }
    };

    return { ...upload, files, errors, progress, getFileReferences, dispatch };
}

function uploadEntrySize(file: UploadEntry) {
    return file.client_size ?? file.size ?? 0;
}

function isUploadConfig(value: unknown): value is UploadConfigShape {
    return Boolean(
        value && typeof value === "object" &&
        typeof (value as UploadConfigShape).ref === "string" &&
        typeof (value as UploadConfigShape).name === "string" &&
        Array.isArray((value as UploadConfigShape).entries) &&
        Array.isArray((value as UploadConfigShape).errors)
    );
}

function missingUpload(name: string) {
    const files = ref<UploadEntry[]>([]);
    const errors = computed(() => []);
    const progress = computed(() => 0);
    const warn = () => {
        console.warn(
            `[alva/useAlvaUpload] Missing LiveView upload config for "${name}". ` +
            `Pass the matching upload prop to the LiveVue component.`
        );
    };
    return {
        name, entries: files, files, errors, progress,
        showFilePicker: warn, cancel: () => {}, clear: () => {},
        getFileReferences: () => [],
        dispatch: async () => { warn(); throw new Error("Missing upload config"); },
    };
}
