// This file is auto-generated by Alva.
// Do not edit manually.

import { ref, watch, type Ref, type WatchSource } from "vue";
import { useLiveVue } from "live_vue";
import type { AlvaEvents } from "../events";

export interface AlvaQueryOptions<Input> {
    debounceMs?: number;
    enabled?: boolean | Ref<boolean> | (() => boolean);
}

export interface AlvaQueryReturn<Output> {
    data: Ref<Output | null>;
    loading: Ref<boolean>;
    error: Ref<any | null>;
    refetch: () => Promise<void>;
}

export function useAlvaQuery<
    K extends keyof AlvaEvents,
    Input = AlvaEvents[K]["input"],
    Output = Extract<AlvaEvents[K]["output"], { ok: true }> extends { data: infer D } ? D : never
>(
    queryEvent: K,
    inputGetter: WatchSource<Input>,
    options: AlvaQueryOptions<Input> = {}
): AlvaQueryReturn<Output> {
    const live = useLiveVue();
    const data = ref<Output | null>(null) as Ref<Output | null>;
    const loading = ref(false);
    const error = ref<any | null>(null);

    const debounceMs = options.debounceMs ?? 0;
    let timeoutId: any;

    const isEnabled = () => {
        if (options.enabled === undefined) return true;
        if (typeof options.enabled === "function") return options.enabled();
        if (typeof options.enabled === "object" && "value" in options.enabled) return options.enabled.value;
        return !!options.enabled;
    };

    const fetchQuery = async (currentInput: Input) => {
        if (!isEnabled()) return;
        
        loading.value = true;
        error.value = null;

        return new Promise<void>((resolve) => {
            live.pushEvent(queryEvent as string, currentInput as any, (reply: any) => {
                loading.value = false;
                if (reply.ok) {
                    data.value = reply.data;
                } else {
                    error.value = reply.error;
                }
                resolve();
            });
        });
    };

    const debouncedFetch = (currentInput: Input) => {
        if (debounceMs > 0) {
            clearTimeout(timeoutId);
            timeoutId = setTimeout(() => {
                fetchQuery(currentInput);
            }, debounceMs);
        } else {
            fetchQuery(currentInput);
        }
    };

    watch(inputGetter, (newInput) => {
        debouncedFetch(newInput);
    }, { deep: true, immediate: true });

    return {
        data,
        loading,
        error,
        refetch: async () => {
            const currentInput = typeof inputGetter === "function" ? (inputGetter as any)() : (inputGetter as any).value;
            await fetchQuery(currentInput);
        }
    };
}
