// This file is auto-generated by Alva.
import type { AlvaEvents } from "./events";
import { use_alva_api } from "alva/use_alva_api";

export interface AlvaApi {
  students: {
    archive: (input: AlvaEvents["students.archive"]["input"]) => Promise<AlvaEvents["students.archive"]["output"]>;
    create: (input: AlvaEvents["students.create"]["input"]) => Promise<AlvaEvents["students.create"]["output"]>;
    list: (input: AlvaEvents["students.list"]["input"]) => Promise<AlvaEvents["students.list"]["output"]>;
  };
  test: {
    assign: (input: AlvaEvents["test.assign"]["input"]) => Promise<AlvaEvents["test.assign"]["output"]>;
  };
}

const base_api = use_alva_api<AlvaEvents>();

function create_deep_proxy(path: string[] = []): any {
  return new Proxy(() => {}, {
    get(_target, prop: string) {
      return create_deep_proxy([...path, prop]);
    },
    apply(_target, _this_arg, args) {
      const event_name = path.join('.');
      const ash_call = base_api.call;
      return ash_call(event_name as any, args[0]);
    }
  });
}

export const api = create_deep_proxy() as AlvaApi;
