// This file is auto-generated by Alva.
import type { AlvaEvents } from "./events";
import { use_alva_api } from "alva/use_alva_api";

export interface AlvaApi {
  catalog: {
    adjust_stock: (input: AlvaEvents["catalog.adjust_stock"]["input"]) => Promise<AlvaEvents["catalog.adjust_stock"]["output"]>;
    list_products: (input: AlvaEvents["catalog.list_products"]["input"]) => Promise<AlvaEvents["catalog.list_products"]["output"]>;
    upload_media: (input: AlvaEvents["catalog.upload_media"]["input"]) => Promise<AlvaEvents["catalog.upload_media"]["output"]>;
  };
  sales: {
    begin_processing: (input: AlvaEvents["sales.begin_processing"]["input"]) => Promise<AlvaEvents["sales.begin_processing"]["output"]>;
    create_order: (input: AlvaEvents["sales.create_order"]["input"]) => Promise<AlvaEvents["sales.create_order"]["output"]>;
    fulfill: (input: AlvaEvents["sales.fulfill"]["input"]) => Promise<AlvaEvents["sales.fulfill"]["output"]>;
    list_orders: (input: AlvaEvents["sales.list_orders"]["input"]) => Promise<AlvaEvents["sales.list_orders"]["output"]>;
  };
  support: {
    create: (input: AlvaEvents["support.create"]["input"]) => Promise<AlvaEvents["support.create"]["output"]>;
    get_conversation: (input: AlvaEvents["support.get_conversation"]["input"]) => Promise<AlvaEvents["support.get_conversation"]["output"]>;
    list_conversations: (input: AlvaEvents["support.list_conversations"]["input"]) => Promise<AlvaEvents["support.list_conversations"]["output"]>;
    list_messages: (input: AlvaEvents["support.list_messages"]["input"]) => Promise<AlvaEvents["support.list_messages"]["output"]>;
    send_message: (input: AlvaEvents["support.send_message"]["input"]) => Promise<AlvaEvents["support.send_message"]["output"]>;
  };
}

const base_api = use_alva_api<AlvaEvents>();

function create_deep_proxy(path: string[] = []): any {
  return new Proxy(() => {}, {
    get(_target, prop: string) {
      return create_deep_proxy([...path, prop]);
    },
    apply(_target, _this_arg, args) {
      const event_name = path.join('.');
      const ash_call = base_api.call;
      return ash_call(event_name as any, args[0]);
    }
  });
}

export const api = create_deep_proxy() as AlvaApi;
