// This file is auto-generated by Alva.
import type { AlvaEvents } from "./events";
import { use_alva_api } from "alva/use_alva_api";

export interface AlvaApi {
  catalog: {
    list_products: (input: AlvaEvents["catalog.list_products"]["input"]) => Promise<AlvaEvents["catalog.list_products"]["output"]>;
  };
  sales: {
    create_order: (input: AlvaEvents["sales.create_order"]["input"]) => Promise<AlvaEvents["sales.create_order"]["output"]>;
    list_orders: (input: AlvaEvents["sales.list_orders"]["input"]) => Promise<AlvaEvents["sales.list_orders"]["output"]>;
  };
}

const base_api = use_alva_api<AlvaEvents>();

function create_deep_proxy(path: string[] = []): any {
  return new Proxy(() => {}, {
    get(_target, prop: string) {
      return create_deep_proxy([...path, prop]);
    },
    apply(_target, _this_arg, args) {
      const event_name = path.join('.');
      const ash_call = base_api.call;
      return ash_call(event_name as any, args[0]);
    }
  });
}

export const api = create_deep_proxy() as AlvaApi;
