// This file is auto-generated by Alva.
// Do not edit manually.

import type { LiveResult } from "./types";

export type CustomerStorefrontLiveEvents = {
  "support.join_chat": {
    input: { customer_name: string };
    output: LiveResult<void>;
  };

  "support.reset_chat": {
    input: Record<string, never>;
    output: LiveResult<void>;
  };

};
