// This file is auto-generated by Alva.
// Do not edit manually.

import type { LiveResult } from "./types";
import type * as Types from "./types";

export type AlvaEvents = {
  "catalog.adjust_stock": {
    input: {
              id: string;
              stock?: number;
            };
    output: LiveResult<Types.Product>;
  };

  "catalog.list_products": {
    input: Record<string, never>;
    output: LiveResult<Types.Product[]>;
  };

  "catalog.upload_media": {
    input: {
              media: File;
              id: string;
            };
    output: LiveResult<Types.Product>;
  };

  "sales.begin_processing": {
    input: {
              id: string;
            };
    output: LiveResult<Types.Order>;
  };

  "sales.create_order": {
    input: {
              customer_name: string;
              product_id: string;
              quantity?: number;
            };
    output: LiveResult<Types.Order>;
  };

  "sales.fulfill": {
    input: {
              id: string;
            };
    output: LiveResult<Types.Order>;
  };

  "sales.list_orders": {
    input: Record<string, never>;
    output: LiveResult<Types.Order[]>;
  };

  "support.create": {
    input: {
              customer_name: string;
            };
    output: LiveResult<Types.Conversation>;
  };

  "support.get_conversation": {
    input: {
              customer_name: string;
            };
    output: LiveResult<Types.Conversation[]>;
  };

  "support.list_conversations": {
    input: Record<string, never>;
    output: LiveResult<Types.Conversation[]>;
  };

  "support.list_messages": {
    input: {
              conversation_id: string;
            };
    output: LiveResult<Types.SupportMessage[]>;
  };

  "support.send_message": {
    input: {
              text: string;
              sender: "shopper" | "merchant";
              conversation_id: string;
            };
    output: LiveResult<Types.SupportMessage>;
  };

};
