// This file is auto-generated by Alva.
// Do not edit manually.

import type { LiveResult } from "./types";
import type * as Types from "./types";

export type AlvaEvents = {
  "catalog.adjust_stock": {
    input: {
              id: string;
              stock?: number;
            };
    output: LiveResult<Types.Product>;
  };

  "catalog.list_products": {
    input: {
              query?: string;
              max_stock?: number;
            };
    output: LiveResult<Types.Product[]>;
  };

  "catalog.upload_media": {
    input: {
              media: string;
              id: string;
            };
    output: LiveResult<Types.Product>;
  };

  "demo_chat.list_messages": {
    input: Record<string, never>;
    output: LiveResult<Types.ChatMessage[]>;
  };

  "demo_chat.send_message": {
    input: {
              author: string;
              text: string;
            };
    output: LiveResult<Types.ChatMessage>;
  };

  "demo_feed.list_entries": {
    input: Record<string, never>;
    output: LiveResult<Types.FeedEntry[]>;
  };

  "demo_notifications.send": {
    input: {
              title: string;
              severity: "info" | "success" | "warning";
            };
    output: LiveResult<Types.Notification>;
  };

  "sales.begin_processing": {
    input: {
              id: string;
            };
    output: LiveResult<Types.Order>;
  };

  "sales.create_order": {
    input: {
              customer_name: string;
              product_id: string;
              quantity?: number;
            };
    output: LiveResult<Types.Order>;
  };

  "sales.fulfill": {
    input: {
              id: string;
            };
    output: LiveResult<Types.Order>;
  };

  "sales.list_orders": {
    input: {
              status?: "new" | "processing" | "fulfilled";
              customer_query?: string;
              product_query?: string;
            };
    output: LiveResult<Types.Order[]>;
  };

  "support.create": {
    input: {
              customer_name: string;
            };
    output: LiveResult<Types.Conversation>;
  };

  "support.get_conversation": {
    input: {
              customer_name: string;
            };
    output: LiveResult<Types.Conversation[]>;
  };

  "support.list_conversations": {
    input: {
              customer_query?: string;
              needs_merchant_reply?: boolean;
            };
    output: LiveResult<Types.Conversation[]>;
  };

  "support.list_messages": {
    input: {
              conversation_id?: string;
            };
    output: LiveResult<Types.SupportMessage[]>;
  };

  "support.send_message": {
    input: {
              text: string;
              sender: "shopper" | "merchant";
              conversation_id: string;
            };
    output: LiveResult<Types.SupportMessage>;
  };

};
