// This file is auto-generated by Alva.
// Do not edit manually.

import type { LiveResult } from "./types";
import type * as Types from "./types";

export type AlvaEvents = {
  "catalog.list_products": {
    input: Record<string, never>;
    output: LiveResult<Types.Product[]>;
  };

  "sales.begin_processing": {
    input: Record<string, never>;
    output: LiveResult<Types.Order>;
  };

  "sales.create_order": {
    input: {
              customer_name: string;
              product_id: string;
              quantity?: number;
            };
    output: LiveResult<Types.Order>;
  };

  "sales.fulfill": {
    input: Record<string, never>;
    output: LiveResult<Types.Order>;
  };

  "sales.list_orders": {
    input: Record<string, never>;
    output: LiveResult<Types.Order[]>;
  };

};
