// This file is auto-generated by Alva.
// Do not edit manually.

import type { LiveResult } from "./types";

export type MerchantConsoleLiveEvents = {
  "support.select_conversation": {
    input: { conversation_id: string };
    output: LiveResult<void>;
  };

};
