// This file is auto-generated by Alva.
// Do not edit manually.

import type { AlvaResult } from "./types";

export type MerchantConsoleLiveEvents = {
  "support.select_conversation": {
    input: { conversation_id?: string };
    output: AlvaResult<void>;
  };

  "console.filter_orders": {
    input: { status?: string; customer_query?: string; product_query?: string };
    output: AlvaResult<void>;
  };

  "console.filter_inventory": {
    input: { query?: string; low_stock_only?: boolean };
    output: AlvaResult<void>;
  };

  "console.filter_conversations": {
    input: { customer_query?: string; waiting_on_merchant_only?: boolean };
    output: AlvaResult<void>;
  };

};
