// This file is auto-generated by Alva.
// Do not edit manually.

import type * as Types from "./types";

export type AlvaSignals = {
  "demo_notifications.sent": {
    payload: Types.Notification;
  };

};
