// This file is auto-generated by Alva.
// Do not edit manually.

import type * as Types from "./types";

export type AlvaSubscriptions = {
  "sales_orders": {
    kind: "stream";
    input: { status?: string | null; sort?: string | null; require_customer?: boolean | null; customer_query?: string | null; product_query?: string | null; };
    item: Types.Order;
  };

  "products": {
    kind: "stream";
    input: { sort?: string | null; query?: string | null; max_stock?: number | null; };
    item: Types.Product;
  };

  "conversations": {
    kind: "stream";
    input: { sort?: string | null; needs_merchant_reply?: boolean | null; customer_query?: string | null; };
    item: Types.Conversation;
  };

  "support_messages": {
    kind: "stream";
    input: { conversation_id?: string | null; };
    item: Types.SupportMessage;
  };

  "feed_entries": {
    kind: "stream";
    input: { sort?: string | null; page?: Record<string, any> | null; };
    item: Types.FeedEntry;
  };

  "chat_messages": {
    kind: "stream";
    input: Record<string, never>;
    item: Types.ChatMessage;
  };

  "demo_notifications_sent": {
    kind: "signal";
    input: Record<string, never>;
    payload: Types.Notification;
  };

};
