// This file is auto-generated by Alva.
// Do not edit manually.

import type * as Types from "./types";

export type AlvaSubscriptions = {
  "support_messages": {
    kind: "stream";
    input: { conversation_id: string; };
    item: Types.SupportMessage;
  };

};
