// This file is auto-generated by Alva.
// Do not edit manually.

export interface AlvaError {
  type?: string;
  message: string;
  code?: string;
  fields?: Record<string, string[]>;
  [key: string]: unknown;
}

export type AlvaResult<T> =
  | { ok: true; data: T; meta?: Record<string, unknown> }
  | { ok: false; error: AlvaError; meta?: Record<string, unknown> };

export interface PaginationInput {
  limit?: number;
  offset?: number;
  after?: string;
  before?: string;
  count?: boolean;
}

export interface BaseFieldFilter<T> {
  eq?: T | null;
  not_eq?: T | null;
  in?: T[] | null;
  is_nil?: boolean | null;
  less_than?: T | null;
  greater_than?: T | null;
  less_than_or_equal?: T | null;
  greater_than_or_equal?: T | null;
}

export interface StringFieldFilter extends BaseFieldFilter<string> {
  contains?: string | null;
  ilike?: string | null;
  like?: string | null;
}

export interface IntFieldFilter extends BaseFieldFilter<number> {}

export interface BooleanFieldFilter {
  eq?: boolean | null;
  not_eq?: boolean | null;
  is_nil?: boolean | null;
}

export interface ProductFilter {
  and?: ProductFilter[];
  or?: ProductFilter[];
  not?: ProductFilter;
  id?: StringFieldFilter | null;
  name?: StringFieldFilter | null;
  description?: StringFieldFilter | null;
  price?: IntFieldFilter | null;
  stock?: IntFieldFilter | null;
  media_reference?: StringFieldFilter | null;
}


export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  stock: number;
  media_reference: string;
}


export interface ChatMessage {
  id: string;
  author: string;
  text: string;
  created_at: string;
}


export interface FeedEntry {
  id: string;
  title: string;
  summary: string;
  position: number;
}


export interface Notification {
  id: string;
  title: string;
  severity: "info" | "success" | "warning" | "danger" | "error";
  created_at: string;
}


export interface Order {
  id: string;
  customer_name: string;
  quantity: number;
  lifecycle_status: "new" | "processing" | "fulfilled";
  created_at: string;
  product_id: string;
  product?: Product;
}


export interface Conversation {
  id: string;
  customer_name: string;
  last_message_at?: string;
  last_message_preview?: string;
  last_message_sender?: "shopper" | "merchant";
  needs_merchant_reply: boolean;
  message_count: number;
  messages?: SupportMessage[];
}


export interface SupportMessage {
  id: string;
  text: string;
  sender: "shopper" | "merchant";
  created_at: string;
  conversation_id: string;
  conversation?: Conversation;
}

