// This file is auto-generated by Alva.
// Do not edit manually.

export type LiveResult<T> =
  | { ok: true; data: T; meta?: Record<string, any> }
  | { ok: false; error: any; meta?: Record<string, any> };

export interface BaseFieldFilter<T> {
  eq?: T | null;
  not_eq?: T | null;
  in?: T[] | null;
  is_nil?: boolean | null;
  less_than?: T | null;
  greater_than?: T | null;
  less_than_or_equal?: T | null;
  greater_than_or_equal?: T | null;
}

export interface StringFieldFilter extends BaseFieldFilter<string> {
  contains?: string | null;
  ilike?: string | null;
  like?: string | null;
}

export interface IntFieldFilter extends BaseFieldFilter<number> {}

export interface BooleanFieldFilter {
  eq?: boolean | null;
  not_eq?: boolean | null;
  is_nil?: boolean | null;
}



export interface Student {
  id: string;
  name: string;
  status?: any;
}

