// This file is auto-generated by Alva.
// Do not edit manually.

import { ref } from "vue";
import { vi } from "vitest";

export function createMockAlvaClient(initialData: Record<string, any> = {}) {
    const createMockQuery = (key: string, defaultVal: any) => {
        const data = ref(initialData[key] ?? defaultVal);
        const loading = ref(false);
        const error = ref(null);
        return {
            data,
            loading,
            error,
            refetch: async () => {}
        };
    };

    const createMockFn = (defaultReturn: any = { ok: true }) => {
        return vi.fn((input: any) => Promise.resolve(defaultReturn));
    };

    return {
        catalog: {
            use_list_products_query: (getter: any) => createMockQuery("products", []),
            use_get_product_by_id: (id: any) => createMockQuery("product", null),
            adjust_stock: createMockFn(),
            upload_media: createMockFn(),
        },
        sales: {
            use_list_orders_query: (getter: any) => createMockQuery("orders", []),
            create_order: createMockFn(),
            begin_processing: createMockFn(),
            fulfill: createMockFn(),
        },
        support: {
            use_list_conversations_query: (getter: any) => createMockQuery("conversations", []),
            use_list_messages_query: (getter: any) => createMockQuery("messages", []),
            create: createMockFn(),
            send_message: createMockFn(),
        },
        demo_chat: {
            use_list_messages_query: (getter: any) => createMockQuery("chat_messages", []),
            send_message: createMockFn(),
        },
        demo_notifications: {
            send: createMockFn(),
        }
    };
}
